[2023-06-24 14:50:58,062] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-06-24T14:50:56.958659+00:00 [queued]>
[2023-06-24 14:50:58,081] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-06-24T14:50:56.958659+00:00 [queued]>
[2023-06-24 14:50:58,083] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-24 14:50:58,085] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-06-24 14:50:58,086] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-24 14:50:58,119] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2023-06-24 14:50:56.958659+00:00
[2023-06-24 14:50:58,128] {standard_task_runner.py:52} INFO - Started process 148 to run task
[2023-06-24 14:50:58,136] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2023-06-24T14:50:56.958659+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpbtr8_vzu', '--error-file', '/tmp/tmp_jwspi03']
[2023-06-24 14:50:58,138] {standard_task_runner.py:80} INFO - Job 14: Subtask load_seed_data_once
[2023-06-24 14:50:58,233] {task_command.py:369} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-06-24T14:50:56.958659+00:00 [running]> on host eaf24e454131
[2023-06-24 14:50:58,387] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2023-06-24T14:50:56.958659+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-24T14:50:56.958659+00:00
[2023-06-24 14:50:58,391] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-24 14:50:58,393] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd dbt && dbt seed --profiles-dir .']
[2023-06-24 14:50:58,410] {subprocess.py:85} INFO - Output:
[2023-06-24 14:50:58,412] {subprocess.py:92} INFO - bash: line 1: cd: dbt: No such file or directory
[2023-06-24 14:50:58,413] {subprocess.py:96} INFO - Command exited with return code 1
[2023-06-24 14:50:58,447] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-24 14:50:58,457] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20230624T145056, start_date=20230624T145058, end_date=20230624T145058
[2023-06-24 14:50:58,490] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task load_seed_data_once (Bash command failed. The command returned a non-zero exit code 1.; 148)
[2023-06-24 14:50:58,510] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-24 14:50:58,569] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
